version: "3.9"

services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ./integration:/workspace
    environment:
      TF_LOG: WARN
    entrypoint: ["/bin/sh", "-c"]
    command: |
      terraform init && \
      terraform apply -auto-approve && \
      terraform destroy -auto-approve
