name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.2
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...

  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.2
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v8.0.0
          install-mode: goinstall
      - name: Run golangci-lint
        run: golangci-lint run . 
